name: Keep Render App Alive

on:
  schedule:
    - cron: "*/7 * * * *" # Every 7 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ping Render App
        run: |
          node <<'EOF'
          const https = require("https");

          const url = "https://task-manager-inertia-django.onrender.com";
          const now = new Date();
          const hour = now.getUTCHours() + 1; // UTC is 1 hour behind WAT

          // Skip quiet hours
          if (hour >= 23 || hour < 6) {
            console.log("⏸️ Skipping ping: quiet hours.");
            process.exit(0);
          }

          // Random chance: ~every 7–12 min (by skipping some runs)
          const chance = Math.random();
          if (chance < 0.6) { // about 60% of the time, it will ping
            https.get(url, (res) => {
              console.log(`✅ Pinged ${url}, status: ${res.statusCode}`);
            }).on("error", (err) => {
              console.error("❌ Error:", err.message);
              process.exit(1);
            });
          } else {
            console.log("⏭️ Skipping this run (random delay emulation).");
          }
          EOF
