name: Keep Render App Alive

on:
  schedule:
    - cron: "*/7 5-21 * * *" # every 7 minutes excluding quiet time 6:00-22:59 UTC
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Restore ping timestamp
        id: cache
        uses: actions/cache@v4
        with:
          path: .last-ping
          key: ping-timestamp

      - name: Ping Render App
        run: |
          node <<'EOF'
          const fs = require("fs");
          const https = require("https");

          const url = "https://task-manager-inertia-django.onrender.com";
          const now = new Date();
          const hour = now.getUTCHours() + 1; // adjust if needed
          const tsFile = ".last-ping";

          // Skip quiet hours
          if (hour >= 23 || hour < 6) {
            console.log("⏸️ Skipping ping: quiet hours.");
            process.exit(0);
          }

          // Read last ping timestamp if exists
          let lastPing = 0;
          if (fs.existsSync(tsFile)) {
            lastPing = parseInt(fs.readFileSync(tsFile, "utf8"), 10) || 0;
          }

          const elapsedMin = (Date.now() - lastPing) / 60000;
          const forcePing = elapsedMin >= 12;

          if (forcePing || Math.random() < 0.6) {
            console.log(forcePing ? "⏰ Forced ping (>=12 min)" : "🎲 Random ping");
            const req = https.get(url, (res) => {
              console.log(`✅ Pinged ${url}, status: ${res.statusCode}`);

              res.on("data", () => {}); // drain data
              res.on("end", () => {
                fs.writeFileSync(tsFile, String(Date.now())); // update timestamp
                console.log("🔚 Response ended cleanly.");
                process.exit(0);
              });
            });

            req.on("error", (err) => {
              console.error("❌ Error:", err.message);
              process.exit(1);
            });
          } else {
            console.log("⏭️ Skipping this run (random delay emulation).");
            process.exit(0);
          }
          EOF

      - name: Save ping timestamp
        if: success()
        uses: actions/cache@v4
        with:
          path: .last-ping
          key: ping-timestamp
